services:
  - type: web
    name: wtg-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        value: https://wtg-telegram-bot.onrender.com
      - key: PORT
        value: 10000
    healthCheckPath: /health
